import nodemailer from "nodemailer";
import Mailgen from "mailgen";

// ─── Transporter ──────────────────────────────────────────────────────────────
const createTransporter = () =>
  nodemailer.createTransport({
    host:   process.env.SMTP_HOST,
    port:   Number(process.env.SMTP_PORT),
    secure: Number(process.env.SMTP_PORT) === 465,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

// ─── Mailgen instance ─────────────────────────────────────────────────────────
const mailGenerator = new Mailgen({
  theme: "default",
  product: {
    name: process.env.APP_NAME || "VideoTube",
    link: process.env.CLIENT_URL || "http://localhost:3000",
    logo: "", // optional: URL to your logo
  },
});

// ─── Core send function ───────────────────────────────────────────────────────
/**
 * Sends an HTML email generated by Mailgen.
 * @param {{ to: string, subject: string, mailgenContent: object }} options
 */
export const sendEmail = async ({ to, subject, mailgenContent }) => {
  const html = mailGenerator.generate(mailgenContent);
  const text = mailGenerator.generatePlaintext(mailgenContent);

  const transporter = createTransporter();
  await transporter.sendMail({
    from:    `"${process.env.APP_NAME || "VideoTube"}" <${process.env.SMTP_USER}>`,
    to,
    subject,
    html,
    text,
  });
};

// ─── Email Content Factories ──────────────────────────────────────────────────

/**
 * Email verification content.
 */
export const emailVerificationContent = (username, verificationUrl) => ({
  body: {
    name: username,
    intro: "Welcome to VideoTube! We're excited to have you on board.",
    action: {
      instructions: "To verify your email address, please click the button below. This link expires in 24 hours.",
      button: {
        color:  "#6C63FF",
        text:   "Verify My Email",
        link:   verificationUrl,
      },
    },
    outro: "If you did not create a VideoTube account, please ignore this email.",
  },
});

/**
 * Forgot password email content.
 */
export const forgotPasswordContent = (username, resetUrl) => ({
  body: {
    name: username,
    intro: "You have received this email because a password reset request for your account was received.",
    action: {
      instructions: "Click the button below to reset your password. This link expires in 24 hours.",
      button: {
        color:  "#DC2626",
        text:   "Reset Your Password",
        link:   resetUrl,
      },
    },
    outro: "If you did not request a password reset, please ignore this email and your password will remain unchanged.",
  },
});
